### ISSUE TITLE
images do not appear in opensea

### ISSUE THREAD

**Issue by santanaruben** [stevegachau/MintBot#4]
good job, everything looks great, the only thing that doesn't seem to work are the ipfs links to the images.

https://opensea.io/assets/matic/0xfd8cfcd710823f89bd533f88a113797040c330c6/407006407998

**Comment by stevegachau** [comment]
You can use the 'refresh metadata' button on Opensea if the image does not appear.

**Comment by santanaruben** [comment]
Awesome, thank you!
